In [1]:
from PIL import Image
import numpy as np
import import_ipynb
import encrypt_mod1_with_transformation as encrypt1
import encrypt_mod2_with_transformation as encrypt2
# Open the PNG image
image = Image.open("lena1.png")
#image2=Image.open("lena_gray.png")

# Convert the image to RGB mode
image_rgb = image.convert("RGB")

# Split the RGB channels
r, g, b = image_rgb.split()

# Save each channel as separate images (optional)
r.save("red1.png")
g.save("green1.png")
b.save("blue1.png")
print(image.size)
print(r.size)

importing Jupyter notebook from encrypt_mod1_with_transformation.ipynb
importing Jupyter notebook from encrypt_mod2_with_transformation.ipynb
(512, 512)
(512, 512)


In [2]:
#red
submatrices=encrypt1.submatrix(r)
rotated_array=encrypt1.transformation1()
m3=encrypt1.divide(submatrices,rotated_array)


In [3]:
m4=encrypt1.zigzag(m3)

In [4]:
rotated_matrix=encrypt1.rotated(m4)

In [5]:
output_matrix=encrypt2.combine(rotated_matrix)

In [6]:
rotated_permute_array=encrypt2.transformation()
permuted_matrix_list=encrypt2.permute(output_matrix,rotated_permute_array)

In [7]:
pixel_vector=encrypt2.pixel_vec(permuted_matrix_list)

In [8]:
pixel_vector=encrypt2.pixel_vec(permuted_matrix_list)

x0: 0.7068


In [9]:
xor_res=encrypt2.xor(key,pixel_vector)

In [10]:
res_arr=encrypt2.encrypt_image(xor_res)
image1=Image.fromarray(res_arr)
image1.save('red_enc.png')


[[22 79 65 ... 254 139 80]
 [188 193 216 ... 229 56 56]
 [0 117 62 ... 54 171 92]
 ...
 [133 121 237 ... 182 33 229]
 [129 80 176 ... 27 121 69]
 [248 165 183 ... 147 114 143]]
512


In [11]:
#green
submatrices=encrypt1.submatrix(g)
rotated_array=encrypt1.transformation1()
m3=encrypt1.divide(submatrices,rotated_array)

In [12]:
m4=encrypt1.zigzag(m3)

In [13]:
rotated_matrix=encrypt1.rotated(m4)

In [14]:
output_matrix=encrypt2.combine(rotated_matrix)

In [15]:
rotated_permute_array=encrypt2.transformation()
permuted_matrix_list=encrypt2.permute(output_matrix,rotated_permute_array)

In [16]:
pixel_vector=encrypt2.pixel_vec(permuted_matrix_list)

In [17]:
key,mu2,x2=encrypt2.key_generation(g)


x0: 0.3884


In [18]:
xor_res=encrypt2.xor(key,pixel_vector)

In [19]:
res_arr=encrypt2.encrypt_image(xor_res)
image2=Image.fromarray(res_arr)
image2.save('green_enc.png')


[[230 107 147 ... 171 33 180]
 [89 141 93 ... 31 224 16]
 [36 179 102 ... 82 92 210]
 ...
 [221 105 248 ... 42 11 176]
 [11 237 23 ... 220 112 193]
 [58 200 36 ... 207 51 242]]
512


In [20]:
#blue
submatrices=encrypt1.submatrix(b)
rotated_array=encrypt1.transformation1()
m3=encrypt1.divide(submatrices,rotated_array)

In [21]:
m4=encrypt1.zigzag(m3)

In [22]:
rotated_matrix=encrypt1.rotated(m4)

In [23]:
output_matrix=encrypt2.combine(rotated_matrix)

In [24]:
rotated_permute_array=encrypt2.transformation()
permuted_matrix_list=encrypt2.permute(output_matrix,rotated_permute_array)

In [25]:
pixel_vector=encrypt2.pixel_vec(permuted_matrix_list)

In [26]:
key,mu3,x3=encrypt2.key_generation(b)


x0: 0.4134


In [27]:
xor_res=encrypt2.xor(key,pixel_vector)

In [28]:
res_arr=encrypt2.encrypt_image(xor_res)
image3=Image.fromarray(res_arr)
image3.save('blue_enc.png')


[[155 242 100 ... 28 79 69]
 [168 31 107 ... 228 75 124]
 [98 5 93 ... 3 209 199]
 ...
 [31 45 93 ... 85 34 94]
 [9 203 82 ... 80 212 82]
 [241 246 99 ... 143 89 163]]
512


In [29]:
image1.show()
image2.show()
image3.show()
combined_image = Image.merge("RGB", (image1,image2,image3))


# Save the combined image
combined_image.save("final_enc.png")
combined_image.show()

print("Images combined successfully!")

Images combined successfully!
